name: 🐛 上报 BUG (Report bug)
description: 烦请您帮助我们进步(Create a report to help us improve).
title: '[Bug]: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        感谢您能抽出时间填写这个 BUG 表单.(Thanks for taking the time to fill out this bug report!)

  - type: dropdown
    id: os
    attributes:
      label: ⚙️ OS
      description: 您用的是什么系统?
      options:
        - Windows(Default)
        - Linux
        - Android
        - Apple

  - type: input
    id: os-version
    attributes:
      label: 📄 请告诉我们您的系统版本(OS Version).
      description: 进一步确定系统信息 (Further determine the system information).
      placeholder: OS Version!

  - type: dropdown
    id: architecture
    attributes:
      label: ⚙️ Architecture
      description: 芯片指令集是哪种?
      options:
        - Any(Default)
        - Arm64
        - Arm32
        - x64
        - x86
        - macOS Rosetta 2
        - LoongArch
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: 📄 请描述您的问题(Describe the bug).
      description: 请清晰简洁地描述您遇到的 BUG (A clear and concise description of what the bug is).
      placeholder: Bug Details!
    validations:
      required: true

  - type: textarea
    id: how-happened
    attributes:
      label: ⭕ BUG 重现(To Reproduce).
      description: 重现步骤(Steps to reproduce the behavior).
      placeholder: Bug Reproduce!
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: 📱 您的联系方式(Contact Details).
      description: 如果我们需要进一步的沟通,如何找到您? (How can we get in touch with you if we need more info?)
      placeholder: ex. email@example.com
    validations:
      required: false
